import { MdOutlineKeyboardArrowRight } from 'react-icons/md';
import Footer from './Components/Footer';
import './globals.css';
import Navbar from './Components/Navbar';
import Social from './Social';
import Skeleton from './Skeleton';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Skeleton content={children}/>
      </body>
    </html>
  )
}
